#define VERTICES 10
#define POPUPLATION_SIZE 50
#define CHROMOSOME_LENGTH (VERTICES - 1)
#define STARTING_VERTICE 0
#define MUTATION_PROBABILITY 0.1
#define NUMBER_OF_POPULATIONS 10000
#define DEVIATION 0
#define POPULATION_INFO 100
#define CROSSOVER_PROBABILITY 0.6